---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident Protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: Personnalisez les paramètres par défaut de Trident Protect pour répondre à vos besoins spécifiques. 
---
= Personnaliser l'installation de Trident Protect
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez personnaliser la configuration par défaut de Trident Protect pour répondre aux exigences spécifiques de votre environnement.



== Spécifiez les limites de ressources du conteneur Trident Protect

Vous pouvez utiliser un fichier de configuration pour spécifier les limites de ressources des conteneurs Trident Protect après l'installation de Trident Protect. La définition de limites de ressources vous permet de contrôler la quantité de ressources du cluster consommées par les opérations de Trident Protect.

.Étapes
. Créez un fichier nommé `resourceLimits.yaml`.
. Renseignez le fichier avec les options de limite de ressources pour les conteneurs Trident Protect en fonction des besoins de votre environnement.
+
L'exemple de fichier de configuration suivant montre les paramètres disponibles et contient les valeurs par défaut pour chaque limite de ressource :

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. Appliquer les valeurs du `resourceLimits.yaml` fichier :
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== Personnaliser les contraintes de contexte de sécurité

Vous pouvez utiliser un fichier de configuration pour modifier les contraintes de contexte de sécurité OpenShift (SCC) pour les conteneurs Trident Protect après avoir installé Trident Protect. Ces contraintes définissent les restrictions de sécurité des pods dans un cluster Red Hat OpenShift.

.Étapes
. Créez un fichier nommé `sccconfig.yaml`.
. Ajoutez l'option SCC au fichier et modifiez les paramètres en fonction des besoins de votre environnement.
+
L'exemple suivant montre les valeurs par défaut des paramètres de l'option SCC :

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
Ce tableau décrit les paramètres de l'option SCC :

+
|===
| Paramètre | Description | Valeur par défaut 


| création | Détermine si une ressource SCC peut être créée. Une ressource SCC ne sera créée que si est défini sur `true` et que `scc.create` le processus d'installation de Helm identifie un environnement OpenShift. Si ne fonctionne pas sur OpenShift ou si `scc.create` est défini sur `false`, aucune ressource SCC ne sera créée. | vrai 


| nom | Spécifie le nom du SCC. | travail-protection-Trident 


| priorité | Définit la priorité du SCC. Les SCC ayant des valeurs de priorité plus élevées sont évalués avant ceux ayant des valeurs plus faibles. | 1 
|===
. Appliquer les valeurs du `sccconfig.yaml` fichier :
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
Les valeurs par défaut seront remplacées par celles spécifiées dans le `sccconfig.yaml` fichier.





== Configurer les connexions NetApp AutoSupport pour Trident Protect

Vous pouvez modifier la façon dont Trident Protect se connecte au support NetApp pour télécharger les modules de support en configurant un proxy pour la connexion.  Vous pouvez configurer le proxy pour utiliser une connexion sécurisée ou non sécurisée selon vos besoins.

[role="tabbed-block"]
====
.Configurer une connexion proxy sécurisée
--
.Étapes
. Configurez une connexion proxy sécurisée pour les chargements des packages de support Trident Protect :
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --reuse-values
----


--
.Configurez une connexion proxy non sécurisée
--
.Étapes
. Configurez une connexion proxy non sécurisée pour les chargements de paquets de support Trident Protect qui ignore la vérification TLS :
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --set autoSupport.insecure=true --reuse-values
----


--
====


== Limiter les pods Trident Protect à des nœuds spécifiques

Vous pouvez utiliser la contrainte de sélection de nœuds nodeSelector de Kubernetes pour contrôler quels nœuds sont éligibles pour exécuter des pods Trident Protect, en fonction des étiquettes de nœud. Par défaut, Trident Protect est limité aux nœuds exécutant Linux. Vous pouvez personnaliser davantage ces contraintes en fonction de vos besoins.

.Étapes
. Créez un fichier nommé `nodeSelectorConfig.yaml`.
. Ajoutez l'option nodeSelector au fichier et modifiez le fichier pour ajouter ou modifier des libellés de nœud afin de les restreindre en fonction des besoins de votre environnement. Par exemple, le fichier suivant contient la restriction par défaut du système d'exploitation, mais cible également une région et un nom d'application spécifiques :
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. Appliquer les valeurs du `nodeSelectorConfig.yaml` fichier :
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
Ceci remplace les restrictions par défaut par celles que vous avez spécifiées dans le `nodeSelectorConfig.yaml` fichier.





== Désactiver les téléchargements quotidiens des modules Trident Protect AutoSupport

Vous pouvez désactiver, si vous le souhaitez, le téléchargement quotidien programmé des modules de support Trident Protect AutoSupport .


NOTE: Par défaut, Trident Protect collecte des informations de support utiles pour toute demande d'assistance NetApp que vous pourriez ouvrir, notamment les journaux, les métriques et les informations de topologie concernant les clusters et les applications gérées.  Trident Protect envoie quotidiennement ces modules de support à NetApp .  Vous pouvez manuellementlink:trident-protect-generate-support-bundle.html["générer un bundle de support"] à tout moment.

.Étapes
. Créez un fichier nommé `autosupportconfig.yaml`.
. Ajoutez l'option AutoSupport au fichier et modifiez les paramètres en fonction des besoins de votre environnement.
+
L'exemple suivant montre les valeurs par défaut des paramètres de l'option AutoSupport :

+
[source, yaml]
----
autoSupport:
  enabled: true
----
+
Lorsque `autoSupport.enabled` est défini sur `false`, les téléchargements quotidiens des packs de support AutoSupport sont désactivés.

. Appliquer les valeurs du `autosupportconfig.yaml` fichier :
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f autosupportconfig.yaml --reuse-values
----

